# Ansatz: Karma im Docker-Container ausführen

# Stage 1: Anwendung bauen
FROM node:16-buster as buildcontainer
# Google Chrome installieren
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -yq google-chrome-stable
# Tests ausführen und Build starten
WORKDIR /usr/src/app
COPY . ./
RUN npm install
RUN npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox
RUN npm run build

# Stage 2: Webserver starten
FROM nginx
LABEL maintainer="Ihr Name <you@your.domain>"
COPY nginx/default.conf /etc/nginx/conf.d
COPY --from=buildcontainer /usr/src/app/dist/book-monkey /usr/share/nginx/html
